title:            Whisky Oriented Development
description:      Victoria's programmers' whisky society.
url:              # Site url.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-47125836-1 # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
    external:     true
  - name:         Email
    url:          mailto:whiskydev@gmail.com
    external:     true
  - name:         Facebook
    url:          https://www.facebook.com/whiskydev
    external:     true
    publisher:    true
  - name:         Twitter
    url:          https://twitter.com/whiskydev
    external:     true
    publisher:    true
  - name:         Google+
    url:          https://plus.google.com/104938615413164700753
    external:     true
    publisher:    true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart